handle packageJson.licenses as an object
ubilabs/webpack-node-modules-list pull request #5
Opened 2016-10-31 22:35 UTC by guykisel

Ran into a bug where `packageJson.licenses` can be an object instead of an array, and then we fail to run `.map` against it. Not sure if my fix is especially good, but it does seem to work.

2016-11-01 08:18 UTC, yfr requested changes

2016-11-01 08:18 UTC, yfr commented on index.js
> +    return (packageJson.licenses && packageJson.licenses.type) ||
We do this already in the bottom of the method. Is this really needed here?

2016-11-01 08:18 UTC, yfr commented
Thanks for the request. Just one question ...

2016-11-01 15:42 UTC, guykisel commented on index.js
> +    return (packageJson.licenses && packageJson.licenses.type) ||
Note that here I'm returning `packageJson.licenses` (plural) as opposed to `packageJson.license` (singular). Initially I was going to just reassign `packageJson.license` directly, but that mutates the original. Thoughts?

2016-11-04 01:03 UTC, guykisel commented
@yfr I replied to your question, what do you think? I'm not entirely sure what the best way to handle this is.

2016-11-04 08:44 UTC, yfr commented on index.js
> +    return (packageJson.licenses && packageJson.licenses.type) ||
Sorry, I missed this. 

Yeah, it looks a bit convoluted but I also have no better idea at the moment. Maybe it's a good idea to add a TODO comment to mark the place for refactoring.

2016-11-04 08:45 UTC, yfr commented
I'm sorry, I missed it.

2016-11-23 22:35 UTC, guykisel commented
@yfr Sorry for the delay! I've added a TODO as requested.

2016-11-24 08:32 UTC, yfr approved these changes

2016-11-24 08:32 UTC, merged