add json output format option
ubilabs/webpack-node-modules-list pull request #8
Opened 2016-11-30 18:36 UTC by guykisel

@yfr curious what you think about this. My alternative would be to have my build scripts do a postprocessing step on the markdown to convert it to json, but it would be nicer (for me) if the webpack plugin can natively generate json.

2016-11-30 20:38 UTC, yfr commented
I think it's very cool! Thank you for the effort! Will check on it in the morning!

2016-11-30 21:13 UTC, guykisel commented on index.js
> +    compilation.assets[`${this.options.outputFile}.${this.options.format}`] = {
Note this does change the behavior of the `outputFile` option a little.

2016-12-06 10:49 UTC, yfr requested changes
So for the delay. Was out of office for some days.

2016-12-06 10:49 UTC, yfr commented on README.md
> +This option allows to change the output format. md (markdown) and json are supported.
I would name the option just `markdown` no need for abbreviation here.

2016-12-06 10:49 UTC, yfr commented on index.js
> +    compilation.assets[`${this.options.outputFile}.${this.options.format}`] = {
That`s fine with me.

2016-12-06 21:41 UTC, guykisel commented on README.md
> +This option allows to change the output format. md (markdown) and json are supported.
Sounds good to me, will update this.

2016-12-06 22:11 UTC, guykisel commented
@yfr updated per your suggestions :)

2016-12-07 08:14 UTC, yfr approved these changes

2016-12-07 08:14 UTC, merged

2016-12-07 08:15 UTC, yfr commented
Thank you for this one!

2016-12-07 21:42 UTC, guykisel commented
Awesome! Thanks :)